### PR TITLE
Fix: refresh social views

### LINKED ISSUE #202: Sent/Received friend requests should appear without refreshing

### LINKED ISSUE #221: Refreshing the social views doesn't work as expected

### PR DESCRIPTION
**Pull request by karimassi**
Closes #221 
Closes #202

### CODE REVIEW

File: app/src/main/java/ch/epfl/balelecbud/view/playlist/PlaylistFragment.java [hunk 1]
```diff
@@ -13,20 +13,23 @@
...
 import ch.epfl.balelecbud.utility.recyclerViews.OnRecyclerViewInteractionListener;
 import ch.epfl.balelecbud.utility.recyclerViews.RefreshableRecyclerViewAdapter;
 
+import static com.google.android.material.snackbar.BaseTransientBottomBar.LENGTH_LONG;
+
 public final class PlaylistFragment extends Fragment implements OnRecyclerViewInteractionListener<Track> {
 
     private static final String TAG = PlaylistFragment.class.getSimpleName();
     private SpotifyAppRemote spotifyAppRemote;
+    View view;
```
Comment (Pialex99) [inline app/src/main/java/ch/epfl/balelecbud/view/playlist/PlaylistFragment.java:32]: Can be converted into local variable
