### PR TITLE
Fix layout issues in RVs

### LINKED ISSUE #197: Set paddings and work on the alignements of items in the recycler views

### PR DESCRIPTION
**Pull request by karimassi**
Closes #197 #145

### CODE REVIEW

File: app/src/androidTest/java/ch/epfl/balelecbud/view/schedule/ScheduleFragmentTest.java [hunk 1]
```diff
@@ -79,20 +84,18 @@ public void testRecyclerViewVisible() {
...
         refreshRecyclerView();
 
         onView(withId(R.id.scheduleRecyclerView)).check(matches(hasChildCount(1)));
 
-        mockDatabase.storeDocument(Database.CONCERT_SLOTS_PATH, slot2);
-
-        refreshRecyclerView();
-
-        onView(withId(R.id.scheduleRecyclerView)).check(matches(hasChildCount(2)));
+//        mockDatabase.storeDocument(Database.CONCERT_SLOTS_PATH, slot2);
```
Comment (karimassi) [inline app/src/androidTest/java/ch/epfl/balelecbud/view/schedule/ScheduleFragmentTest.java:94]:
```suggestion

```

File: app/src/main/java/ch/epfl/balelecbud/view/friendship/FriendViewHolder.java [hunk 2]
```diff
@@ -7,16 +7,20 @@
 import androidx.annotation.NonNull;
 import androidx.recyclerview.widget.RecyclerView;
 
+import org.w3c.dom.Text;
+
```
Comment (Pialex99) [inline app/src/main/java/ch/epfl/balelecbud/view/friendship/FriendViewHolder.java:11]: Do you really use it ?

File: app/src/androidTest/java/ch/epfl/balelecbud/view/schedule/ScheduleFragmentTest.java [hunk 3]
```diff
@@ -79,20 +84,17 @@ public void testRecyclerViewVisible() {
...
 
-        mockDatabase.storeDocument(Database.CONCERT_SLOTS_PATH, slot2);
-
-        refreshRecyclerView();
-
-        onView(withId(R.id.scheduleRecyclerView)).check(matches(hasChildCount(2)));
+//
+//        refreshRecyclerView();
+//
+//        onView(withId(R.id.scheduleRecyclerView)).check(matches(hasChildCount(2)));
```
Comment (Pialex99) [inline app/src/androidTest/java/ch/epfl/balelecbud/view/schedule/ScheduleFragmentTest.java:97]: You could remove it 
```suggestion
```
